services:
  senior-pomidor-edge:
    build:
      context: .
      args:
        INSTALL_HARDWARE_DEPS: "true"
    container_name: senior-pomidor-edge
    network_mode: host
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    devices:
      - /dev/i2c-1:/dev/i2c-1
      - /dev/video0:/dev/video0
    volumes:
      - ./data:/app/data
      - /etc/NetworkManager/system-connections:/etc/NetworkManager/system-connections:ro
      - /run/udev:/run/udev:ro
      - /sys/bus/w1:/sys/bus/w1:ro
      - /sys/devices:/sys/devices:ro
    privileged: true
